{% set version = "2021.10.1" %}
# {% set sha256 = "e3d07556034aa0bfffcff55c6051aa55099c8196a2c4ab77450f9a872863d376" %}

package:
  name: restraintlib
  version: {{ version }}

source:
  # url: https://github.com/mkowiel/restraintlib/archive/refs/tags/{{ version }}.tar.gz
  # sha256: {{ sha256 }}
  git_url: https://github.com/mkowiel/restraintlib.git
  git_rev: 2021.10.1py2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python =2.7
    - setuptools
  run:
    - python =2.7
    - scikit-learn <=0.20.4
    - pandas
    - six

# test:
#   imports:
#     - restraintlib
#   requires:
#     - pytest
#   source_files:
#     - tests/*.py
#     - tests/*.cif
#     - tests/*.pdb
#   commands:
#     - pytest

about:
  home: https://github.com/mkowiel/restraintlib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Bond length and angle restraints for DNA and RNA oligonucleotides

extra:
  recipe-maintainers:
    - mkowiel
    - dabrze
